### ISSUE TITLE
Plotting observables of multiple particles

### ISSUE THREAD

**Issue by stevenjeremies** [MadAnalysis/madanalysis5#120]
### Question

Hello,

I want to compare differential distributions between the processes 't t~ a' and 'b l+ vl b~ l- vl~ a' which I both generated with madgraph. I would like to look at top quark observables and compare them with the corresponding ones for the top decay products in the other process. Hence, I defined a multiparticle:

define t_new = b l+ vl

If I now plot observables of t_new is it doing what I intended, i.e. if I plot

plot PT(t_new)

does it simply sum the PT´s of the single particles defined in t_new for each event? Thanks in advance!

**Comment by jackaraz** [comment]
Hi @stevenjeremies, the function you wrote defines a set of particles called `t_new`, which includes all b quarks positive leptons and neutrinos in an event and then loops around all these particles and fills the histogram. I believe this is not what you are looking for. 

First, I believe you are looking for particle-level events, i.e. not showered/hadronized since there is no mention. Depending on the nature of the observable you want to create, you can use `vPT` or `sPT`, where the latter combines scalar $p_T$ values and plots into the histogram ( $\sum_{particle}p^{particle}_T$ ). The former combines four vectors of the particle momentum and plots the $p_T$ distribution for that combined momentum. Also, as you can see in the manual, defining a multiparticle creates a vector which you don't want; you want to choose leptons, b's and neutrinos separately, so you need to input the plot function that you like to use as `b[i]` and/or `l+[i]` where `i` stands for the index of the particle in a PT-ordered particle list.

You can also see what the function is doing by reading the C++ file that MadAnalysis 5 writes for you; it's under `my_submission/Build/SampleAnalyzer/User/Analyzer/user.cpp`.

**Comment by stevenjeremies** [comment]
Hi @jackaraz and thank you for your answer! I understand that what I did was wrong. However, I did not understand the last part in which you described how to use the plot function. Wouldn't be the command

plot sPT(b l+ vl)

enough to plot the scalar sum of the PT's of all these particles for each event? Or putting it in a different way, is the index $i$
necessary to use and if so what is a PT-ordered particle list? I would highly appreciate if you could shortly elaborate on that.

**Comment by jackaraz** [comment]
Hi @stevenjeremies, PT-ordered particle list means if you want to access a collection, for instance, b, these b-quarks will be in a collection ordered with respect to their $p_T$ values. So if you want to access the leading b quark, you need to type `b[1]`. Same for other collections. `plot sPT(b l+ vl)` will sum up all the momenta of all possible combinations of `b`'s, `l+`'s and `vl`'s. If you have strictly one of each in your process, you are fine, but this is not a good habit to have since, in the case of multiple particles in a collection, this notation will double count some of the values. You will see how it's written if you check the `ANALYSIS_<X>/Build/SampleAnalyzer/User/Analyzer/user.cpp` file.
