### ISSUE TITLE
error in compilation of fastjet in madanalysis5 

### ISSUE THREAD

**Issue by 834abdulquddus** [MadAnalysis/madanalysis5#149]
### System Settings

hp ProBook i7
python2.7 and 3.10.6
madanalysis5 v3.4.1

### Describe the bug

           Building SampleAnalyzer libraries     
MA5:    **********************************************************
MA5:    How many cores for the compiling? default = max = 4
   Answer: 4
MA5:    => Number of cores used for the compilation = 4
MA5:    Writing the setup files ...
MA5:    Writing all the Makefiles ...
MA5:    **********************************************************
MA5:    Component 1/9 - test program: SampleAnalyzer configuration
MA5:      - Cleaning the project before building the test program ...
MA5:      - Compiling the source files ...
MA5:      - Linking the test program ...
MA5:      - Checking that the test program is properly built ...
MA5:      - Cleaning the project after building the test program ...
MA5:      - Running the test program ...
MA5:      - Checking the program output...
MA5:       => Status: [OK]
MA5:    **********************************************************
MA5:    Component 2/9 - library: SampleAnalyzer commons
MA5:      - Cleaning the project before building the library ...
MA5:      - Compiling the source files ...
MA5:      - Linking the library ...
MA5:      - Checking that the library is properly built ...
MA5:      - Cleaning the project after building the library ...
MA5:       => Status: [OK]
MA5:    **********************************************************
MA5:    Component 3/9 - test program: SampleAnalyzer commons
MA5:      - Cleaning the project before building the test program ...
MA5:      - Compiling the source files ...
MA5:      - Linking the test program ...
MA5:      - Checking that the test program is properly built ...
MA5:      - Cleaning the project after building the test program ...
MA5:      - Running the test program ...
MA5:      - Checking the program output...
MA5:       => Status: [OK]
MA5:    **********************************************************
MA5:    Component 4/9 - library: interface to FastJet
MA5:      - Cleaning the project before building the library ...
MA5:      - Compiling the source files ...
MA5-ERROR: impossible to compile the project. For more details, see the log file:
MA5-ERROR: /home/abdul/madanalysis17/tools/SampleAnalyzer/Interfaces/compilation_fastjet.log
MA5-ERROR: The library building aborted.

### To Reproduce

error occurs when compile fastjet in madanalysis5 v 3.4.1

### Additional information

please solve this issue*

**Comment by jackaraz** [comment]
Hi, madanalysis does not have version 3.4.1; the latest stable version is 1.10, and hp is a computer brand, not your operating system. As you can read from the error message, madanalysis produces a log file which includes information about the compilation process. We can not help you if you don’t provide proper information about your system and software we are not in your machine, every machine is different. On 29 Nov 2022, at 5:47 am, 834abdulquddus ***@***.***> wrote:﻿
System Settings
hp ProBook i7
python2.7 and 3.10.6
madanalysis5 v3.4.1
Describe the bug
       Building SampleAnalyzer libraries     

MA5:    **********************************************************
MA5:    How many cores for the compiling? default = max = 4
Answer: 4
MA5:    => Number of cores used for the compilation = 4
MA5:    Writing the setup files ...
MA5:    Writing all the Makefiles ...
MA5:    **********************************************************
MA5:    Component 1/9 - test program: SampleAnalyzer configuration
MA5:      - Cleaning the project before building the test program ...
MA5:      - Compiling the source files ...
MA5:      - Linking the test program ...
MA5:      - Checking that the test program is properly built ...
MA5:      - Cleaning the project after building the test program ...
MA5:      - Running the test program ...
MA5:      - Checking the program output...
MA5:       => Status: [OK]
MA5:    **********************************************************
MA5:    Component 2/9 - library: SampleAnalyzer commons
MA5:      - Cleaning the project before building the library ...
MA5:      - Compiling the source files ...
MA5:      - Linking the library ...
MA5:      - Checking that the library is properly built ...
MA5:      - Cleaning the project after building the library ...
MA5:       => Status: [OK]
MA5:    **********************************************************
MA5:    Component 3/9 - test program: SampleAnalyzer commons
MA5:      - Cleaning the project before building the test program ...
MA5:      - Compiling the source files ...
MA5:      - Linking the test program ...
MA5:      - Checking that the test program is properly built ...
MA5:      - Cleaning the project after building the test program ...
MA5:      - Running the test program ...
MA5:      - Checking the program output...
MA5:       => Status: [OK]
MA5:    **********************************************************
MA5:    Component 4/9 - library: interface to FastJet
MA5:      - Cleaning the project before building the library ...
MA5:      - Compiling the source files ...
MA5-ERROR: impossible to compile the project. For more details, see the log file:
MA5-ERROR: /home/abdul/madanalysis17/tools/SampleAnalyzer/Interfaces/compilation_fastjet.log
MA5-ERROR: The library building aborted.
To Reproduce
error occurs when compile fastjet in madanalysis5 v 3.4.1
Expected behaviour
No response
Log files
No response
Additional information
please solve this issue*
