### ISSUE TITLE
The bin ma5 in the substructure branch didn't pass test program

### ISSUE THREAD

**Issue by fortuneteller-y** [MadAnalysis/madanalysis5#163]
### Question

When I use the bin ma5 in the ma5-substructure branch, I run across the error " impossible to link the project .see the log file linking_process.log. The test program building aborted." Please kindly find the error report in the log file as below. Could you help me fix the problem? Additionally, I could not use the command "install HEPTopTagger" in the recent version ma5-1.10,   it seems that there is no this option provided. 

[linking_process.log](https://github.com/MadAnalysis/madanalysis5/files/10314548/linking_process.log)

**Comment by jackaraz** [comment]
Hi @fortuneteller-y, first of all, branch is not a release, I can not guarantee the stability of the software if you choose to use a branch. We extensively test our software before releasing it; hence if its not released that means its not tested so you will need to use it with that in mind. The release that you are looking for is `v2.0.X-beta` which includes all the substructure tools. I suggest checking our tutorials for details on installation and usage. Since you havent provided any details about your system I can not tell whats going on in your machine, I myself not a fortuneteller unfortunately. But I suspect that you are using a preinstalled FastJet version which might not be compiled to our standards. I suggest installing FastJet through ma5 v2.0.X-beta (*not v1.10*) and try it again. Bear in mind that this is a beta version and we are still working on it so please let us know if you see anything fishy in terms of physics.

**Comment by fortuneteller-y** [comment]
Thanks a lot for your reply. I have fixed the problem by installing fastjet through ma5 v2.0 as you suggested.
