### ISSUE TITLE
impossible to compile the project

### ISSUE THREAD

**Issue by RBadawi99** [MadAnalysis/madanalysis5#243]
### Question

Hello!

My system is Ubuntu 22.04, I have downloaded madanalysis5 via MadGraph version MG5_aMC_v3_5_3.
I have encountered an error while running the command as explained in the following ticket:
https://answers.launchpad.net/mg5amcnlo/+question/709251

**in the tag_1_MA5__reco_BasicReco.log file:**

*************************************************************
*        W E L C O M E  to  M A D A N A L Y S I S  5        *
*                                                           *
*   MA5 release : 1.9.60                       2024-02-10   *
*                                                           *
*         Comput. Phys. Commun. 184 (2013) 222-256          *
*             Eur. Phys. J. C74 (2014) 3103                 *
*************************************************************
Executing the commands from the script
...
ma5>define invisible = -14 12 -12 16 14 -16
ma5>set main.fastsim.package = fastjet
ma5>set main.fastsim.algorithm = antikt
ma5>set main.fastsim.radius = 0.4
ma5>set main.fastsim.ptmin = 5.0
ma5>set main.fastsim.bjet_id.matching_dr = 0.4
ma5>set main.fastsim.bjet_id.efficiency = 1.0
ma5>set main.fastsim.bjet_id.misid_cjet = 0.0
ma5>set main.fastsim.bjet_id.misid_ljet = 0.0
ma5>set main.fastsim.tau_id.efficiency = 1.0
ma5>set main.fastsim.tau_id.misid_ljet = 0.0
ma5>import /home/raghad/Downloads/MG5_aMC_v3_5_3/MY_FIRST_MG5_RUN/Events/run_04/tag_1_pythia8_events.hepmc.gz as reco_events
   -> Storing the file 'tag_1_pythia8_events.hepmc.gz' in the dataset 'reco_events'.
ma5>set main.outputfile=tag_1_pythia8_BasicReco.lhe.gz
ma5>submit /home/raghad/Downloads/MG5_aMC_v3_5_3/MY_FIRST_MG5_RUN/MA5_HADRON_ANALYSIS_reco_BasicReco_1
   Creating folder 'MA5_HADRON_ANALYSIS_reco_BasicReco_1'...
   Copying 'SampleAnalyzer' source files...
   Inserting your selection into 'SampleAnalyzer'...
   Writing the list of datasets...
   Writing the command line history...
   Creating Makefiles...
   Compiling 'SampleAnalyzer'...
impossible to compile the project. For more details, see the log file:
/home/raghad/Downloads/MG5_aMC_v3_5_3/MY_FIRST_MG5_RUN/MA5_HADRON_ANALYSIS_reco_BasicReco_1/Build/Log/compilation.log
job submission aborted.
ma5>remove reco_events

**and in the compilation.log file:**

c++ -Wall -std=c++11 -O3 -fPIC -I/home/raghad/Downloads/MG5_aMC_v3_5_3/HEPTools/madanalysis5/madanalysis5/tools/ -I./ -pthread -std=c++11 -m64 -I/home/raghad/root/include -o Main/main.o -c Main/main.cpp
In file included from /home/raghad/root/include/RWrap_libcpp_string_view.h:545,
                 from /home/raghad/root/include/RStringView.h:26,
                 from /home/raghad/root/include/TString.h:28,
                 from /home/raghad/root/include/TNamed.h:26,
                 from /home/raghad/root/include/TDirectory.h:25,
                 from /home/raghad/root/include/TROOT.h:28,
                 from /home/raghad/Downloads/MG5_aMC_v3_5_3/HEPTools/madanalysis5/madanalysis5/tools/SampleAnalyzer/Interfaces/root/RootMainHeaders.h:30,
                 from ./SampleAnalyzer/User/Analyzer/user.h:5,
                 from ./SampleAnalyzer/User/Analyzer/analysisList.h:2,
                 from Main/main.cpp:12:
/home/raghad/root/include/libcpp_string_view.h: In member function ‘constexpr std::experimental::__ROOT::basic_string_view<_CharT, _Traits>::size_type std::experimental::__ROOT::basic_string_view<_CharT, _Traits>::max_size() const’:
/home/raghad/root/include/libcpp_string_view.h:275:62: error: ‘numeric_limits’ is not a member of ‘std’
  275 |         size_type max_size() const _NOEXCEPT { return _VSTD::numeric_limits<size_type>::max(); }
      |                                                              ^~~~~~~~~~~~~~
/home/raghad/root/include/libcpp_string_view.h:275:86: error: expected primary-expression before ‘>’ token
  275 |         size_type max_size() const _NOEXCEPT { return _VSTD::numeric_limits<size_type>::max(); }
      |                                                                                      ^
/home/raghad/root/include/libcpp_string_view.h:275:89: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  275 |         size_type max_size() const _NOEXCEPT { return _VSTD::numeric_limits<size_type>::max(); }
      |                                                                                         ^~~
      |                                                                                         std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from /home/raghad/Downloads/MG5_aMC_v3_5_3/HEPTools/madanalysis5/madanalysis5/tools/SampleAnalyzer/Commons/DataFormat/WeightCollection.h:35,
                 from /home/raghad/Downloads/MG5_aMC_v3_5_3/HEPTools/madanalysis5/madanalysis5/tools/SampleAnalyzer/Commons/DataFormat/MCEventFormat.h:37,
                 from /home/raghad/Downloads/MG5_aMC_v3_5_3/HEPTools/madanalysis5/madanalysis5/tools/SampleAnalyzer/Commons/DataFormat/EventFormat.h:36,
                 from /home/raghad/Downloads/MG5_aMC_v3_5_3/HEPTools/madanalysis5/madanalysis5/tools/SampleAnalyzer/Process/Core/SampleAnalyzer.h:38,
                 from Main/main.cpp:11:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
make: *** [Makefile:101: Main/main.o] Error 1

And I do not get the plots and histograms as I finish.
Any help?
Many thanks.

**Comment by jackaraz** [comment]
Hi @RBadawi99 have you tried with the latest version of Ma5? Your version is quite outdated.

**Comment by RBadawi99** [comment]
Hello @jackaraz, thank you for responding.
I have not downloaded Ma5 independently. In the MadGraph shell, I ran "install MadAnalysis5" and it downloaded on it own.
Can you explain further how to download the latest version of Ma5 within MG5?

**Comment by jackaraz** [comment]
Hi @RBadawi99, you can find the details on madgraph workflow in their documentation.

**Comment by RBadawi99** [comment]
Hello @jackaraz,
Thanks for responding.

I have tried to install MA5 like indicated here: https://github.com/MadAnalysis/madanalysis5/?tab=readme-ov-file
And I have indicated this error:

raghad@raghad-IdeaPad-L3-15IML05:~/Downloads/madanalysis5-1.10.12$ ./bin/ma5
MA5: 
MA5: *************************************************************
MA5: *                                                           *
MA5: *        W E L C O M E  to  M A D A N A L Y S I S  5        *
MA5: *                         ______  ______                    *
MA5: *                 /'\_/`\/\  __ \/\  ___\                   *
MA5: *                /\      \ \ \_\ \ \ \__/                   *
MA5: *                \ \ \__\ \ \  __ \ \___``\                 *
MA5: *                 \ \ \_/\ \ \ \/\ \/\ \_\ \                *
MA5: *                  \ \_\\ \_\ \_\ \_\ \____/                *
MA5: *                   \/_/ \/_/\/_/\/_/\/___/                 *
MA5: *                                                           *
MA5: *   MA5 release : 1.10.12                      2023/09/13   *
MA5: *                                                           *
MA5: *         Comput. Phys. Commun. 184 (2013) 222-256          *
MA5: *             Eur. Phys. J. C74 (2014) 3103                 *
MA5: *                                                           *
MA5: *   The MadAnalysis Development Team - Please visit us at   *
MA5: *              https://github.com/MadAnalysis               *
MA5: *                                                           *
MA5: *              Type 'help' for in-line help.                *
MA5: *                                                           *
MA5: *************************************************************
MA5: Platform: Linux 6.5.0-17-generic [Linux mode]
MA5: Reading user settings ...
MA5: Checking mandatory packages:
MA5:      - Python                   [OK]
MA5:      - GNU GCC g++              [OK]
MA5:      - GNU Make                 [OK]
MA5: Checking optional packages devoted to data processing:
MA5:      - Zlib                     [OK]
MA5:      - FastJet                  [OK]
MA5-ERROR: impossible to execute the commands: /usr/bin/root-config --libdir --incdir --version
MA5:      - Root                     [OK]
MA5:      - Delphes                  [DISABLED]
MA5:      - Delphes-MA5tune          [DISABLED]
MA5: Checking the MadAnalysis 5 core library:
MA5:   => First use of MadAnalysis (or the library is missing).
MA5: 
MA5:    **********************************************************
MA5:                 Building SampleAnalyzer libraries     
MA5:    **********************************************************
MA5:    How many cores for the compiling? default = max = 8
   Answer: 8
MA5:    => Number of cores used for the compilation = 8
MA5:    Writing the setup files ...
MA5:    Writing all the Makefiles ...
MA5:    **********************************************************
MA5:    Component 1/11 - test program: SampleAnalyzer configuration
MA5:      - Cleaning the project before building the test program ...
MA5:      - Compiling the source files ...
MA5:      - Linking the test program ...
MA5:      - Checking that the test program is properly built ...
MA5:      - Cleaning the project after building the test program ...
MA5:      - Running the test program ...
MA5:      - Checking the program output...
MA5:       => Status: [OK]
MA5:    **********************************************************
MA5:    Component 2/11 - library: SampleAnalyzer commons
MA5:      - Cleaning the project before building the library ...
MA5:      - Compiling the source files ...
MA5:      - Linking the library ...
MA5:      - Checking that the library is properly built ...
MA5:      - Cleaning the project after building the library ...
MA5:       => Status: [OK]
MA5:    **********************************************************
MA5:    Component 3/11 - test program: SampleAnalyzer commons
MA5:      - Cleaning the project before building the test program ...
MA5:      - Compiling the source files ...
MA5:      - Linking the test program ...
MA5:      - Checking that the test program is properly built ...
MA5:      - Cleaning the project after building the test program ...
MA5:      - Running the test program ...
MA5:      - Checking the program output...
MA5:       => Status: [OK]
MA5:    **********************************************************
MA5:    Component 4/11 - library: interface to zlib
MA5:      - Cleaning the project before building the library ...
MA5:      - Compiling the source files ...
MA5:      - Linking the library ...
MA5:      - Checking that the library is properly built ...
MA5:      - Cleaning the project after building the library ...
MA5:       => Status: [OK]
MA5:    **********************************************************
MA5:    Component 5/11 - test program: interface to zlib
MA5:      - Cleaning the project before building the test program ...
MA5:      - Compiling the source files ...
MA5:      - Linking the test program ...
MA5:      - Checking that the test program is properly built ...
MA5:      - Cleaning the project after building the test program ...
MA5:      - Running the test program ...
MA5:      - Checking the program output...
MA5:       => Status: [OK]
MA5:    **********************************************************
MA5:    Component 6/11 - library: interface to FastJet
MA5:      - Cleaning the project before building the library ...
MA5:      - Compiling the source files ...
MA5-ERROR: impossible to compile the project. For more details, see the log file:
MA5-ERROR: /home/raghad/Downloads/madanalysis5-1.10.12/tools/SampleAnalyzer/Interfaces/compilation_fastjet.log
MA5-ERROR: The library building aborted.
raghad@raghad-IdeaPad-L3-15IML05:~/Downloads/madanalysis5-1.10.12$ 

Can you help?

Many thanks.

**Comment by jackaraz** [comment]
hi @RBadawi99 we need more information about the error you are getting, can you send the log file i.e. ``/home/raghad/Downloads/madanalysis5-1.10.12/tools/SampleAnalyzer/Interfaces/compilation_fastjet.log``

**Comment by RBadawi99** [comment]
[compilation_fastjet.log](https://github.com/MadAnalysis/madanalysis5/files/14468708/compilation_fastjet.log)
Thank you for answering.
Kindly see the file attached.

**Comment by jackaraz** [comment]
Hi @RBadawi99, it looks like you are using a fastjet that is not compiled with ma5 requirements. Have you installed fastjet through ma5 >v1.10?

**Comment by RBadawi99** [comment]
Hello @jackaraz, I have only downloaded the from here https://github.com/MadAnalysis/madanalysis5/?tab=readme-ov-file and did not try any other source for its packages.

**Comment by jackaraz** [comment]
Hi @RBadawi99 I'm talking about FastJet not madanalysis. If you read the error that you are getting its not from madanalysis but the third party packages that you have.

**Comment by baozhiyang-hep** [comment]
Hello!

I encountered a similar issue, and I will describe it in detail below: I am using Ubuntu 18.04.6 LTS, with gcc (g++) version 9.4.0. Taking the results of version madanalysis5-1.10.12 as an example, I ran ./bin/ma5 in the folder. During the compilation of the 6th component, the following error occurred: 
MA5:    **********************************************************
MA5:    Component 6/11 - library: interface to FastJet
MA5:      - Cleaning the project before building the library ...
MA5:      - Compiling the source files ...
MA5-ERROR: impossible to compile the project. For more details, see the log file:
MA5-ERROR: /home/tev/Desktop/bzy/combine_testing/madanalysis5-1.10.12/madanalysis5-1.10.12/tools/SampleAnalyzer/Interfaces/compilation_fastjet.log
MA5-ERROR: The library building aborted.

The contents of the compilation_fastjet.log file are as follows:
1 c++ -Wall -std=c++11 -O3 -fPIC -I/home/tev/Desktop/bzy/combine_testing/madanalysis5-1.10.12/madanalysis5-1.10.12/tools/ -I/usr/include -o fastjet/ClusterAlgoCDFMidpoint.o -c fastjet/ClusterAlgoCDFMidpoint.cp    p$
  2 c++ -Wall -std=c++11 -O3 -fPIC -I/home/tev/Desktop/bzy/combine_testing/madanalysis5-1.10.12/madanalysis5-1.10.12/tools/ -I/usr/include -o fastjet/ClusterAlgoStandard.o -c fastjet/ClusterAlgoStandard.cpp$
  3 c++ -Wall -std=c++11 -O3 -fPIC -I/home/tev/Desktop/bzy/combine_testing/madanalysis5-1.10.12/madanalysis5-1.10.12/tools/ -I/usr/include -o fastjet/ClusterAlgoCDFJetClu.o -c fastjet/ClusterAlgoCDFJetClu.cpp$
  4 c++ -Wall -std=c++11 -O3 -fPIC -I/home/tev/Desktop/bzy/combine_testing/madanalysis5-1.10.12/madanalysis5-1.10.12/tools/ -I/usr/include -o fastjet/DJRextractor.o -c fastjet/DJRextractor.cpp$
  5 c++ -Wall -std=c++11 -O3 -fPIC -I/home/tev/Desktop/bzy/combine_testing/madanalysis5-1.10.12/madanalysis5-1.10.12/tools/ -I/usr/include -o fastjet/ClusterAlgoGridJet.o -c fastjet/ClusterAlgoGridJet.cpp$
  6 c++ -Wall -std=c++11 -O3 -fPIC -I/home/tev/Desktop/bzy/combine_testing/madanalysis5-1.10.12/madanalysis5-1.10.12/tools/ -I/usr/include -o fastjet/ClusterAlgoSISCone.o -c fastjet/ClusterAlgoSISCone.cpp$
  7 c++ -Wall -std=c++11 -O3 -fPIC -I/home/tev/Desktop/bzy/combine_testing/madanalysis5-1.10.12/madanalysis5-1.10.12/tools/ -I/usr/include -o fastjet/ClusterAlgoFastJet.o -c fastjet/ClusterAlgoFastJet.cpp$
  8 fastjet/ClusterAlgoCDFMidpoint.cpp:31:10: fatal error: fastjet/CDFMidPointPlugin.hh: No such file or directory$
  9  #include <fastjet/CDFMidPointPlugin.hh>$
 10           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~$
 11 compilation terminated.$
 12 Makefile_fastjet:89: recipe for target 'fastjet/ClusterAlgoCDFMidpoint.o' failed$
 13 make: *** [fastjet/ClusterAlgoCDFMidpoint.o] Error 1$
 14 make: *** Waiting for unfinished jobs....$
 15 fastjet/ClusterAlgoCDFJetClu.cpp:31:10: fatal error: fastjet/CDFJetCluPlugin.hh: No such file or directory$
 16  #include <fastjet/CDFJetCluPlugin.hh>$
 17           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~$
 18 compilation terminated.$
 19 Makefile_fastjet:89: recipe for target 'fastjet/ClusterAlgoCDFJetClu.o' failed$
 20 make: *** [fastjet/ClusterAlgoCDFJetClu.o] Error 1$
 21 fastjet/ClusterAlgoGridJet.cpp:31:10: fatal error: fastjet/GridJetPlugin.hh: No such file or directory$
 22  #include <fastjet/GridJetPlugin.hh>$
 23           ^~~~~~~~~~~~~~~~~~~~~~~~~~$
 24 compilation terminated.$
 25 Makefile_fastjet:89: recipe for target 'fastjet/ClusterAlgoGridJet.o' failed$
 26 make: *** [fastjet/ClusterAlgoGridJet.o] Error 1$
 27 fastjet/ClusterAlgoSISCone.cpp:31:10: fatal error: fastjet/SISConePlugin.hh: No such file or directory$
 28  #include <fastjet/SISConePlugin.hh>$
 29           ^~~~~~~~~~~~~~~~~~~~~~~~~~$
 30 compilation terminated.$
 31 Makefile_fastjet:89: recipe for target 'fastjet/ClusterAlgoSISCone.o' failed$
 32 make: *** [fastjet/ClusterAlgoSISCone.o] Error 1$

I searched for the locations of the .cpp and .h files mentioned in the `compilation_fastjet.log` file and found them under `tools/SampleAnalyzer/Interfaces/fastjet`.(The `ls` command was executed after running `./bin/ma5`.)
(base) tev@alien-14:~/Desktop/bzy/combine_testing/madanalysis5-1.10.12/madanalysis5-1.10.12/tools/SampleAnalyzer/Interfaces/fastjet$ ls
ClusterAlgoCDFJetClu.cpp  ClusterAlgoCDFMidpoint.cpp  ClusterAlgoFastJet.cpp  ClusterAlgoFastJet.o    ClusterAlgoGridJet.h  ClusterAlgoSISCone.cpp  ClusterAlgoStandard.cpp  ClusterAlgoStandard.o  DJRextractor.h
ClusterAlgoCDFJetClu.h    ClusterAlgoCDFMidpoint.h    ClusterAlgoFastJet.h    ClusterAlgoGridJet.cpp  ClusterAlgoPlugin.h   ClusterAlgoSISCone.h    ClusterAlgoStandard.h    DJRextractor.cpp       DJRextractor.o


However, based on the information in the log file, it seems that the compiler is trying to compile files such as tools/fastjet/ClusterAlgoCDFMidpoint.cpp, but these files do not exist. 

So, I tried to add new paths to the compilation options so that the compiler could find these files. However, every time I run `./bin/ma5`, the `Makefile_fastjet` gets reloaded, making it impossible to modify. The compilation options in the `Makefile_fastjet` file under `tools/SampleAnalyzer/Interfaces` are as follows:
# C++ Compilation options
CXXFLAGS  = -Wall -std=c++11 -O3 -fPIC -I$(MA5_BASE)/tools/
CXXFLAGS += $(shell $(MA5_BASE)/tools/SampleAnalyzer/ExternalSymLink/Bin/fastjet-config --cxxflags)


The above are the details of the issue I encountered. I would like to ask for your advice on where the root of the problem lies and how it should be resolved.

**Comment by BFuks** [comment]
Hi,

Please try to veto fastjet (in `madanalysis/input/installation_options.dat`) and reinstall it later on (by typing `install fastjet`).

Cheers,

Benjamin
