### ISSUE TITLE
Importing two models within one submitted job

### ISSUE THREAD

**Issue by parhamdehghani** [MadAnalysis/madanalysis5#37]
### Question

Hello,

I have simulated the background processes employing SM while my signal process has been elicited from a BSM model. So I have to incorporate both models to do the analysis and compare the events after stringent cuts. The problem is that muon is considered as e2 in my model but mu- in SM! I have checked to define based on PDG id but it does not work in the SampleAnalyzer compilation. Is there any way to work out this issue and include both models while different datasets regarding my model and SM are read? Thanks for your help

**Comment by jackaraz** [comment]
Hi @parhamdehghani MadAnalysis directly uses PDGID's of the particles that are written in any given MC output file, not symbolic abbreviations. From what you wrote, I understand that your particles have different PDGID's and you want to study the phenomenology of this new particle, correct? Because muons are well defined in MadAnalysis and it doesn't matter which name you assign to them, you can give your name to tag them as multiparticles if you like but in the backend, they will be called via their PDGID. So if you are using a particle with unconventional PDGID, you can define your new particle in [here](https://github.com/MadAnalysis/madanalysis5/blob/main/tools/SampleAnalyzer/particle.tbl) and MadAnalysis will automatically recognize it, but if your particle is ordinary muon it is already defined; hence I would need more information on what you are trying to do. 

Cheers
